const P_BEL_FLOW_ROUTE_BASIC_DATA = "/datosBasicos";
const P_BEL_FLOW_ROUTE_QUOTE = "/cotizacion";
const P_BEL_FLOW_ROUTE_PAYMENT_PLAN = "/planDePagos";
const P_BEL_FLOW_ROUTE_ADD_DATA = "/datosAdicionales";
const P_BEL_FLOW_ROUTE_IMAGES = "/imagenes";

const P_BEL_PAYMENT_FLOW_ROUTE_METHOD = "/metodoDePago";
const P_BEL_PAYMENT_FLOW_ROUTE_POLICY_DETAIL = "/detalleDePoliza";
const P_BEL_PAYMENT_FLOW_ROUTE_INSURANCE = "/seguroContratado";

const ROUTE_NOT_FOUND = "*";

export {
  P_BEL_FLOW_ROUTE_BASIC_DATA,
  P_BEL_FLOW_ROUTE_QUOTE,
  P_BEL_FLOW_ROUTE_PAYMENT_PLAN,
  P_BEL_FLOW_ROUTE_ADD_DATA,
  P_BEL_FLOW_ROUTE_IMAGES,
  P_BEL_PAYMENT_FLOW_ROUTE_METHOD,
  P_BEL_PAYMENT_FLOW_ROUTE_POLICY_DETAIL,
  P_BEL_PAYMENT_FLOW_ROUTE_INSURANCE,
  ROUTE_NOT_FOUND,
};
